### ISSUE TITLE
Asciinema to .gif 변환 기능 추가

### ISSUE THREAD

**Issue by congeal** [hdltools/vscode-asciinema-player#3]
## 요구 사항
* [Asciicast2gif](https://github.com/asciinema/asciicast2gif) 기능 추가
* WebView에 변환 버튼으로 .gif 변환 가능
* 커맨드 팔렛트를 통해 .gif 변환 가능

**Comment by whiteout1024** [comment]
asciicast2gif 설치 후 cast 파일 변환을 시도하는 경우 아래와 같은 error가 있습니다.
환경 문제인지 asciicast2gif module의 문제인지 확인이 필요합니다.
Ubuntu 환경에 아래와 같은 package를 system에 설치했습니다.
- phantomjs
- gifsicle

❯ ./node_modules/asciicast2gif/asciicast2gif ../exampleFiles/333393.cast temp.fig
==> Loading ../exampleFiles/333393.cast...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
/home/whiteout/work/nodejs/vscode-asciinema-player/web/node_modules/asciicast2gif/main.js:697
Qe)}function ep(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;}}function fp(a,b,c){c=Zo(c,dp(function(c){a[2]=c;a[1]=b;return ep(a)}));return r(c)?(a[2]=Nb(c),a[1]=b,dj):null}function gp(a,b){a=a[6];null!=b&&a.Dc(null,b,dp(function(){return function(){return null}}(a)));Yo(a);return a}
                                                                                                   ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at of (/home/whiteout/work/nodejs/vscode-asciinema-player/web/node_modules/asciicast2gif/main.js:706:266)
    at Function.e [as c] (/home/whiteout/work/nodejs/vscode-asciinema-player/web/node_modules/asciicast2gif/main.js:293:156)
    at /home/whiteout/work/nodejs/vscode-asciinema-player/web/node_modules/asciicast2gif/main.js:295:256
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
